In [158]:
import os
from dotenv import load_dotenv
from google.cloud import storage
import pandas as pd
from io import BytesIO

load_dotenv()

True

In [159]:
SEASON = int(os.getenv("SEASON", ""))

GCS_BUCKET = os.getenv("GCS_BUCKET", "").strip()
GCS_MEDAL = os.getenv("GCS_MEDAL", "").strip()
BLOB_PATH = f"{GCS_MEDAL}/season={SEASON}/session.parquet"

In [160]:
print(f"[INFO] Fetching sessions for season {SEASON}")
client = storage.Client()
blob = client.bucket(GCS_BUCKET).blob(BLOB_PATH)

df = pd.read_parquet(BytesIO(blob.download_as_bytes()))
df.to_csv("../../data/silver/sessions.csv")

[INFO] Fetching sessions for season 2026

In [161]:
df = df.drop(columns=["session_type"], errors="coerce")

In [162]:
df.isna().sum()

session_key           0
session_name          0
date_start            0
date_end              0
meeting_key           0
circuit_key           0
circuit_short_name    0
country_key           0
country_code          0
country_name          0
location              0
gmt_offset            0
year                  0
is_cancelled          0
ingested_at           0
dtype: int64

In [163]:
df.duplicated().sum()

np.int64(0)

In [164]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 126 entries, 0 to 125
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   session_key         126 non-null    int64
 1   session_name        126 non-null    object
 2   date_start          126 non-null    object
 3   date_end            126 non-null    object
 4   meeting_key         126 non-null    int64
 5   circuit_key         126 non-null    int64
 6   circuit_short_name  126 non-null    object
 7   country_key         126 non-null    int64
 8   country_code        126 non-null    object
 9   country_name        126 non-null    object
 10  location            126 non-null    object
 11  gmt_offset          126 non-null    object
 12  year                126 non-null    int64
 13  is_cancelled        126 non-null    bool
 14  ingested_at         126 non-null    datetime64[us, UTC]
dtypes: bool(1), datetime64[us, UTC](1), int64(5), object(8)
memory usage: 14.0+ KB

**SESSION KEY**

In [165]:
duplicate_session_key = df.loc[df["session_key"].duplicated()]
duplicate_session_key

Empty DataFrame
Columns: [session_key, session_name, date_start, date_end, meeting_key, circuit_key, circuit_short_name, country_key, country_code, country_name, location, gmt_offset, year, is_cancelled, ingested_at]
Index: []

In [166]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 126 entries, 0 to 125
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   session_key         126 non-null    int64
 1   session_name        126 non-null    object
 2   date_start          126 non-null    object
 3   date_end            126 non-null    object
 4   meeting_key         126 non-null    int64
 5   circuit_key         126 non-null    int64
 6   circuit_short_name  126 non-null    object
 7   country_key         126 non-null    int64
 8   country_code        126 non-null    object
 9   country_name        126 non-null    object
 10  location            126 non-null    object
 11  gmt_offset          126 non-null    object
 12  year                126 non-null    int64
 13  is_cancelled        126 non-null    bool
 14  ingested_at         126 non-null    datetime64[us, UTC]
dtypes: bool(1), datetime64[us, UTC](1), int64(5), object(8)
memory usage: 14.0+ KB

**SESSION NAME**

In [167]:
df["session_name"].value_counts()
for i in range(1, 4):
    df.loc[df["session_name"] == f"Day {i}", "session_name"] = f"Testing Day {i}"

**DATE START**

In [168]:
df["date_start"] = pd.to_datetime(df["date_start"])
df["date_end"] = pd.to_datetime(df["date_end"])

**MEETING KEY**

In [169]:
df["meeting_key"].value_counts()

meeting_key
1280    5
1279    5
1283    5
1284    5
1281    5
1282    5
1285    5
1286    5
1288    5
1287    5
1295    5
1296    5
1289    5
1290    5
1291    5
1292    5
1293    5
1294    5
1299    5
1300    5
1297    5
1298    5
1301    5
1302    5
1304    3
1305    3
Name: count, dtype: int64

**CIRCUIT KEY**

In [170]:
df["circuit_key"].value_counts()

circuit_key
63     11
10      5
49      5
46      5
149     5
151     5
23      5
22      5
15      5
19      5
2       5
7       5
4       5
55      5
39      5
153     5
144     5
61      5
9       5
65      5
14      5
152     5
150     5
70      5
Name: count, dtype: int64

**CIRCUIT SHORT NAME**

In [171]:
df["circuit_short_name"] = df["circuit_short_name"].str.strip()
df["circuit_short_name"].value_counts()

circuit_short_name
Sakhir                11
Melbourne              5
Shanghai               5
Suzuka                 5
Jeddah                 5
Miami                  5
Montreal               5
Monte Carlo            5
Catalunya              5
Spielberg              5
Silverstone            5
Spa-Francorchamps      5
Hungaroring            5
Zandvoort              5
Monza                  5
Madring                5
Baku                   5
Singapore              5
Austin                 5
Mexico City            5
Interlagos             5
Las Vegas              5
Lusail                 5
Yas Marina Circuit     5
Name: count, dtype: int64

**COUNTRY_KEY**

In [172]:
df["country_key"].value_counts()

country_key
19     15
36     11
1      10
5       5
53      5
153     5
4       5
46      5
114     5
17      5
2       5
16      5
14      5
133     5
13      5
30      5
157     5
8       5
10      5
149     5
21      5
Name: count, dtype: int64

**COUNTRY NAME**

In [173]:
df["country_name"] = df["country_name"].str.strip()
df["country_name"].value_counts()

country_name
United States           15
Bahrain                 11
Spain                   10
Australia                5
China                    5
Saudi Arabia             5
Japan                    5
Canada                   5
Monaco                   5
Austria                  5
United Kingdom           5
Belgium                  5
Hungary                  5
Netherlands              5
Italy                    5
Azerbaijan               5
Singapore                5
Mexico                   5
Brazil                   5
Qatar                    5
United Arab Emirates     5
Name: count, dtype: int64

**LOCATION**

In [174]:
df["location"] = df["location"].str.strip()
df["location"].value_counts()

location
Bahrain              6
Melbourne            5
Shanghai             5
Suzuka               5
Sakhir               5
Jeddah               5
Miami Gardens        5
Montréal             5
Monte Carlo          5
Barcelona            5
Spielberg            5
Silverstone          5
Spa-Francorchamps    5
Budapest             5
Zandvoort            5
Monza                5
Madrid               5
Baku                 5
Marina Bay           5
Austin               5
Mexico City          5
São Paulo            5
Las Vegas            5
Lusail               5
Yas Marina           5
Name: count, dtype: int64

**TIME OFFSET**

In [175]:
df["gmt_offset"] = pd.to_timedelta(df["gmt_offset"])
df["gmt_offset"].value_counts()

gmt_offset
0 days 02:00:00      40
0 days 03:00:00      21
-1 days +20:00:00    10
0 days 08:00:00      10
0 days 04:00:00      10
0 days 11:00:00       5
0 days 09:00:00       5
0 days 01:00:00       5
-1 days +19:00:00     5
-1 days +18:00:00     5
-1 days +21:00:00     5
-1 days +16:00:00     5
Name: count, dtype: int64

**IS CANCELLED**

In [176]:
df["is_cancelled"] = df["is_cancelled"].astype(bool)
df["is_cancelled"].value_counts()

is_cancelled
False    116
True      10
Name: count, dtype: int64

In [179]:
ingested_at = pd.Timestamp.now(tz="UTC")
df["ingested_at"] = ingested_at

In [180]:
df.head()

,session_key,session_name,date_start,date_end,meeting_key,circuit_key,circuit_short_name,country_key,country_code,country_name,location,gmt_offset,year,is_cancelled,ingested_at
0,11465,Testing Day 1,2026-02-11 07:00:00+00:00,2026-02-11 16:00:00+00:00,1304,63,Sakhir,36,BRN,Bahrain,Bahrain,0 days 03:00:00,2026,False,2026-05-04 09:13:57.063016+00:00
1,11466,Testing Day 2,2026-02-12 07:00:00+00:00,2026-02-12 16:00:00+00:00,1304,63,Sakhir,36,BRN,Bahrain,Bahrain,0 days 03:00:00,2026,False,2026-05-04 09:13:57.063016+00:00
2,11467,Testing Day 3,2026-02-13 07:00:00+00:00,2026-02-13 16:00:00+00:00,1304,63,Sakhir,36,BRN,Bahrain,Bahrain,0 days 03:00:00,2026,False,2026-05-04 09:13:57.063016+00:00
3,11470,Testing Day 1,2026-02-18 07:00:00+00:00,2026-02-18 16:00:00+00:00,1305,63,Sakhir,36,BRN,Bahrain,Bahrain,0 days 03:00:00,2026,False,2026-05-04 09:13:57.063016+00:00
4,11469,Testing Day 2,2026-02-19 07:00:00+00:00,2026-02-19 16:00:00+00:00,1305,63,Sakhir,36,BRN,Bahrain,Bahrain,0 days 03:00:00,2026,False,2026-05-04 09:13:57.063016+00:00

In [181]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 126 entries, 0 to 125
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   session_key         126 non-null    int64
 1   session_name        126 non-null    object
 2   date_start          126 non-null    datetime64[ns, UTC]
 3   date_end            126 non-null    datetime64[ns, UTC]
 4   meeting_key         126 non-null    int64
 5   circuit_key         126 non-null    int64
 6   circuit_short_name  126 non-null    object
 7   country_key         126 non-null    int64
 8   country_code        126 non-null    object
 9   country_name        126 non-null    object
 10  location            126 non-null    object
 11  gmt_offset          126 non-null    timedelta64[ns]
 12  year                126 non-null    int64
 13  is_cancelled        126 non-null    bool
 14  ingested_at         126 non-null    datetime64[us, UTC]
dtypes: bool(1), datetime64[ns, UTC](2), datetime64[us, UTC](1), int64(5), object(5), timedelta64[ns](1)
memory usage: 14.0+ KB